// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpLyKSkCtfEYJOgo6WQoYxf0Y-7TNYLXc',
    appId: '1:924472443301:web:4a6c5c1db0b4340980284c',
    messagingSenderId: '924472443301',
    projectId: 'prog-1f748',
    authDomain: 'prog-1f748.firebaseapp.com',
    storageBucket: 'prog-1f748.firebasestorage.app',
    measurementId: 'G-CQTY6TSZL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBHiRN00R7hvFlz--Zfie0nqkV_4rUxvc',
    appId: '1:924472443301:android:bf69a5a7aafc9be780284c',
    messagingSenderId: '924472443301',
    projectId: 'prog-1f748',
    storageBucket: 'prog-1f748.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAygwJW-gb0ZsloKpDTXFUnJ5xyFsYhvnY',
    appId: '1:924472443301:ios:25d22897652b93f880284c',
    messagingSenderId: '924472443301',
    projectId: 'prog-1f748',
    storageBucket: 'prog-1f748.firebasestorage.app',
    iosBundleId: 'com.example.prog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAygwJW-gb0ZsloKpDTXFUnJ5xyFsYhvnY',
    appId: '1:924472443301:ios:25d22897652b93f880284c',
    messagingSenderId: '924472443301',
    projectId: 'prog-1f748',
    storageBucket: 'prog-1f748.firebasestorage.app',
    iosBundleId: 'com.example.prog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpLyKSkCtfEYJOgo6WQoYxf0Y-7TNYLXc',
    appId: '1:924472443301:web:ac4f3f5c5385bf1c80284c',
    messagingSenderId: '924472443301',
    projectId: 'prog-1f748',
    authDomain: 'prog-1f748.firebaseapp.com',
    storageBucket: 'prog-1f748.firebasestorage.app',
    measurementId: 'G-FJEGBJL69K',
  );
}
