# Define a global platform for your project
platform :ios, '12.0'

target 'Runner' do
  # Use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# Post-install script for Flutter compatibility
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end